name: Deploy Script

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
          source: "./"
          target: ${{ secrets.APP_PATH }}

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            # move to project directory
            cd ${{ secrets.APP_PATH }} && \
            # upload new ENV
            echo "${{secrets.ENV}}" > .env && \
            # install npm packages
            npm install && npm run build && npm run migrate:up && npm run start:staging
            # remove git folders
            rm -rf .git && \
            rm -rf .github && \
            cd ~  && \
            rm -rf .github
