name: Deploy Script

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.PROD_SSH_HOST }}
          USERNAME: ${{ secrets.PROD_SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
          source: "./"
          target: ${{ secrets.PROD_PATH }}

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.PROD_SSH_HOST }}
          USERNAME: ${{ secrets.PROD_SSH_USER }}
          KEY: ${{ secrets.SSH_KEY }}
          script: |
            # move to project directory
            cd ${{ secrets.PROD_PATH }} && \
            # upload new ENV
            echo "${{secrets.PROD_ENV}}" > .env && \
            # install npm packages
            npm install && npm run build && npm run migrate:up && npm run start:prod
            # remove git folders
            rm -rf .git && \
            rm -rf .github && \
            cd ~  && \
            rm -rf .github
