name: Deploy to Staging

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

jobs:
  deploy:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo
          uses: actions/checkout@v3

        - name: use node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'
        - run: npm install
        - run: npx nest build
        - run: rm -rf .git .github  # remove git folders

        - name: Copy file via scp
          uses: appleboy/scp-action@master
          with:
            HOST: ${{ secrets.SSH_HOST }}
            USERNAME: ${{ secrets.SSH_USER }}
            KEY: ${{ secrets.SSH_KEY }}
            source: "./"
            # target: ${{ secrets.APP_PATH }}
            target: /root/apps/sendpouch/staging/gateway-service

        - name: Executing remote  command
          uses: appleboy/ssh-action@master
          with:
            HOST: ${{ secrets.SSH_HOST }}
            USERNAME: ${{ secrets.SSH_USER }}
            KEY: ${{ secrets.SSH_KEY }}
            script: |
              # move to project directory
              cd /root/apps/sendpouch/staging/gateway-service && \
              # upload new ENV
              echo "${{secrets.ENV}}" > .env && \
              # install npm packages
              npm install && npm run start:staging
              echo "Deployment completed ✅"